export function getCustomText(rank, suit) {
    const customTexts = {
        'J♠': 'Jack of Spades',
        'J♥': 'Jack of Hearts',
        'J♦': 'Jack of Diamonds',
        'J♣': 'Jack of Clubs',
        'Q♠': 'Queen of Spades',
        'Q♥': 'Queen of Hearts',
        'Q♦': 'Queen of Diamonds',
        'Q♣': 'Queen of Clubs',
        'K♠': 'King of Spades',
        'K♥': 'King of Hearts',
        'K♦': 'King of Diamonds',
        'K♣': 'King of Clubs',
        /*
        'A♠': 'Ace of Spades',
        'A♥': 'Ace of Hearts',
        'A♦': 'Ace of Diamonds',
        'A♣': 'Ace of Clubs',
        '10♠': 'Ten of Spades',
        '10♥': 'Ten of Hearts',
        '10♦': 'Ten of Diamonds',
        '10♣': 'Ten of Clubs', 
        '9♠': 'Nine of Spades',
        '9♥': 'Nine of Hearts',
        '9♦': 'Nine of Diamonds',
        '9♣': 'Nine of Clubs',
        '8♠': 'Eight of Spades',
        '8♥': 'Eight of Hearts',
        '8♦': 'Eight of Diamonds',
        '8♣': 'Eight of Clubs',    
        '7♠': 'Seven of Spades',
        '7♥': 'Seven of Hearts',
        '7♦': 'Seven of Diamonds',
        '7♣': 'Seven of Clubs',
        '6♠': 'Six of Spades',
        '6♥': 'Six of Hearts',
        '6♦': 'Six of Diamonds',
        '6♣': 'Six of Clubs',  
        '5♠': 'Five of Spades',
        '5♥': 'Five of Hearts',
        '5♦': 'Five of Diamonds',
        '5♣': 'Five of Clubs',
        '4♠': 'Four of Spades',
        '4♥': 'Four of Hearts',
        '4♦': 'Four of Diamonds',
        '4♣': 'Four of Clubs',    
        '3♠': 'Three of Spades',
        '3♥': 'Three of Hearts',
        '3♦': 'Three of Diamonds',
        '3♣': 'Three of Clubs',
        '2♠': 'Two of Spades',
        '2♥': 'Two of Hearts',
        '2♦': 'Two of Diamonds',
        '2♣': 'Two of Clubs',
        */
    };
    return customTexts[rank + suit] || ''; // Return custom text or empty string for non-face cards
}

export function getCardLink(rank, suit) {
    const cardLinks = {
        'J♠': { text: 'Learn about the Jack of Spades', url: 'https://en.wikipedia.org/wiki/Jack_(playing_card)#Jack_of_spades' },
        'J♥': { text: 'Learn about the Jack of Hearts', url: 'https://en.wikipedia.org/wiki/Jack_(playing_card)#Jack_of_hearts' },
        'J♦': { text: 'Learn about the Jack of Diamonds', url: 'https://en.wikipedia.org/wiki/Jack_(playing_card)#Jack_of_diamonds' },
        'J♣': { text: 'Learn about the Jack of Clubs', url: 'https://en.wikipedia.org/wiki/Jack_(playing_card)#Jack_of_clubs' },
        'Q♠': { text: 'Learn about the Queen of Spades', url: 'https://en.wikipedia.org/wiki/Queen_(playing_card)#Queen_of_spades' },
        'Q♥': { text: 'Learn about the Queen of Hearts', url: 'https://en.wikipedia.org/wiki/Queen_(playing_card)#Queen_of_hearts' },
        'Q♦': { text: 'Learn about the Queen of Diamonds', url: 'https://en.wikipedia.org/wiki/Queen_(playing_card)#Queen_of_diamonds' },
        'Q♣': { text: 'Learn about the Queen of Clubs', url: 'https://en.wikipedia.org/wiki/Queen_(playing_card)#Queen_of_clubs' },
        'K♠': { text: 'Learn about the King of Spades', url: 'https://en.wikipedia.org/wiki/King_(playing_card)#King_of_spades' },
        'K♥': { text: 'Learn about the King of Hearts', url: 'https://en.wikipedia.org/wiki/King_(playing_card)#King_of_hearts' },
        'K♦': { text: 'Learn about the King of Diamonds', url: 'https://en.wikipedia.org/wiki/King_(playing_card)#King_of_diamonds' },
        'K♣': { text: 'Learn about the King of Clubs', url: 'https://en.wikipedia.org/wiki/King_(playing_card)#King_of_clubs' },

        /*
        'A♠': { text: 'Learn about the Ace of Spades', url: 'https://en.wikipedia.org/wiki/Ace_(playing_card)#Ace_of_spades' },
        'A♥': { text: 'Learn about the Ace of Hearts', url: 'https://en.wikipedia.org/wiki/Ace_(playing_card)#Ace_of_hearts' },
        'A♦': { text: 'Learn about the Ace of Diamonds', url: 'https://en.wikipedia.org/wiki/Ace_(playing_card)#Ace_of_diamonds' },
        'A♣': { text: 'Learn about the Ace of Clubs', url: 'https://en.wikipedia.org/wiki/Ace_(playing_card)#Ace_of_clubs' },  
        '10♠': { text: 'Learn about the Ten of Spades', url: 'https://en.wikipedia.org/wiki/Ten_(playing_card)#Ten_of_spades' },
        '10♥': { text: 'Learn about the Ten of Hearts', url: 'https://en.wikipedia.org/wiki/Ten_(playing_card)#Ten_of_hearts' },
        '10♦': { text: 'Learn about the Ten of Diamonds', url: 'https://en.wikipedia.org/wiki/Ten_(playing_card)#Ten_of_diamonds' },
        '10♣': { text: 'Learn about the Ten of Clubs', url: 'https://en.wikipedia.org/wiki/Ten_(playing_card)#Ten_of_clubs' }, 
        '9♠': { text: 'Learn about the Nine of Spades', url: 'https://en.wikipedia.org/wiki/Nine_(playing_card)#Nine_of_spades' },
        '9♥': { text: 'Learn about the Nine of Hearts', url: 'https://en.wikipedia.org/wiki/Nine_(playing_card)#Nine_of_hearts' },
        '9♦': { text: 'Learn about the Nine of Diamonds', url: 'https://en.wikipedia.org/wiki/Nine_(playing_card)#Nine_of_diamonds' },
        '9♣': { text: 'Learn about the Nine of Clubs', url: 'https://en.wikipedia.org/wiki/Nine_(playing_card)#Nine_of_clubs' },
        '8♠': { text: 'Learn about the Eight of Spades', url: 'https://en.wikipedia.org/wiki/Eight_(playing_card)#Eight_of_spades' },
        '8♥': { text: 'Learn about the Eight of Hearts', url: 'https://en.wikipedia.org/wiki/Eight_(playing_card)#Eight_of_hearts' },
        '8♦': { text: 'Learn about the Eight of Diamonds', url: 'https://en.wikipedia.org/wiki/Eight_(playing_card)#Eight_of_diamonds' },
        '8♣': { text: 'Learn about the Eight of Clubs', url: 'https://en.wikipedia.org/wiki/Eight_(playing_card)#Eight_of_clubs' },    
        '7♠': { text: 'Learn about the Seven of Spades', url: 'https://en.wikipedia.org/wiki/Seven_(playing_card)#Seven_of_spades' },
        '7♥': { text: 'Learn about the Seven of Hearts', url: 'https://en.wikipedia.org/wiki/Seven_(playing_card)#Seven_of_hearts' },
        '7♦': { text: 'Learn about the Seven of Diamonds', url: 'https://en.wikipedia.org/wiki/Seven_(playing_card)#Seven_of_diamonds' },
        '7♣': { text: 'Learn about the Seven of Clubs', url: 'https://en.wikipedia.org/wiki/Seven_(playing_card)#Seven_of_clubs' },
        '6♠': { text: 'Learn about the Six of Spades', url: 'https://en.wikipedia.org/wiki/Six_(playing_card)#Six_of_spades' },
        '6♥': { text: 'Learn about the Six of Hearts', url: 'https://en.wikipedia.org/wiki/Six_(playing_card)#Six_of_hearts' },
        '6♦': { text: 'Learn about the Six of Diamonds', url: 'https://en.wikipedia.org/wiki/Six_(playing_card)#Six_of_diamonds' },
        '6♣': { text: 'Learn about the Six of Clubs', url: 'https://en.wikipedia.org/wiki/Six_(playing_card)#Six_of_clubs' },  
        '5♠': { text: 'Learn about the Five of Spades', url: 'https://en.wikipedia.org/wiki/Five_(playing_card)#Five_of_spades' },
        '5♥': { text: 'Learn about the Five of Hearts', url: 'https://en.wikipedia.org/wiki/Five_(playing_card)#Five_of_hearts' },
        '5♦': { text: 'Learn about the Five of Diamonds', url: 'https://en.wikipedia.org/wiki/Five_(playing_card)#Five_of_diamonds' },
        '5♣': { text: 'Learn about the Five of Clubs', url: 'https://en.wikipedia.org/wiki/Five_(playing_card)#Five_of_clubs' },
        '4♠': { text: 'Learn about the Four of Spades', url: 'https://en.wikipedia.org/wiki/Four_(playing_card)#Four_of_spades' },
        '4♥': { text: 'Learn about the Four of Hearts', url: 'https://en.wikipedia.org/wiki/Four_(playing_card)#Four_of_hearts' },
        '4♦': { text: 'Learn about the Four of Diamonds', url: 'https://en.wikipedia.org/wiki/Four_(playing_card)#Four_of_diamonds' },
        '4♣': { text: 'Learn about the Four of Clubs', url: 'https://en.wikipedia.org/wiki/Four_(playing_card)#Four_of_clubs' },   
        '3♠': { text: 'Learn about the Three of Spades', url: 'https://en.wikipedia.org/wiki/Three_(playing_card)#Three_of_spades' },
        '3♥': { text: 'Learn about the Three of Hearts', url: 'https://en.wikipedia.org/wiki/Three_(playing_card)#Three_of_hearts' },
        '3♦': { text: 'Learn about the Three of Diamonds', url: 'https://en.wikipedia.org/wiki/Three_(playing_card)#Three_of_diamonds' },
        '3♣': { text: 'Learn about the Three of Clubs', url: 'https://en.wikipedia.org/wiki/Three_(playing_card)#Three_of_clubs' },
        '2♠': { text: 'Learn about the Two of Spades', url: 'https://en.wikipedia.org/wiki/Two_(playing_card)#Two_of_spades' },
        '2♥': { text: 'Learn about the Two of Hearts', url: 'https://en.wikipedia.org/wiki/Two_(playing_card)#Two_of_hearts' },
        '2♦': { text: 'Learn about the Two of Diamonds', url: 'https://en.wikipedia.org/wiki/Two_(playing_card)#Two_of_diamonds' },
        '2♣': { text: 'Learn about the Two of Clubs', url: 'https://en.wikipedia.org/wiki/Two_(playing_card)#Two_of_clubs' },  
        */
    };
    return cardLinks[rank + suit] 
    //The below adds a link to all cards without a specified link
    //|| { text: 'Learn more about playing cards', url: 'https://en.wikipedia.org/wiki/Playing_card' };
}


// Map for face card images
export const faceCardImages = {
    'J♠': 'https://j.gifs.com/Kdn4o2.gif',
    'J♥': 'https://media.tenor.com/M-bhqjb_sH8AAAAM/gorilla-dance.gif',
    'J♦': 'https://i.chzbgr.com/full/6609308928/h852784D0/thoughtful-gorilla',
    'J♣': 'https://media0.giphy.com/media/v1.Y2lkPTc5MGI3NjExNDl6eWp5NnYwMmlyeDNuanZyM3pxcjloajFlaW1hYzNueW92NHJyNSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/kDf0eEXhOhlZgdp2dy/giphy.webp',
    'Q♠': 'https://media.tenor.com/RpqiTosprnkAAAAM/ntuni-gorilla.gif',
    'Q♥': 'https://i.makeagif.com/media/9-18-2020/kA60qq.gif',
    'Q♦': 'https://i.chzbgr.com/full/5054283520/h19EE1232/break-dancing-gorilla-at-the-calgary-zoo',
    'Q♣': 'https://media.tenor.com/M-bhqjb_sH8AAAAM/gorilla-dance.gif',
    'K♠': 'https://media.tenor.com/M-bhqjb_sH8AAAAM/gorilla-dance.gif',
    'K♥': 'https://media.tenor.com/M-bhqjb_sH8AAAAM/gorilla-dance.gif',
    'K♦': 'https://media.tenor.com/M-bhqjb_sH8AAAAM/gorilla-dance.gif',
    'K♣': 'https://media.tenor.com/M-bhqjb_sH8AAAAM/gorilla-dance.gif',
    /*
    'A♠': 'https://media.tenor.com/M-bhqjb_sH8AAAAM/gorilla-dance.gif',
    'A♥': 'https://media.tenor.com/M-bhqjb_sH8AAAAM/gorilla-dance.gif',
    'A♦': 'https://media.tenor.com/M-bhqjb_sH8AAAAM/gorilla-dance.gif',
    'A♣': 'https://media.tenor.com/M-bhqjb_sH8AAAAM/gorilla-dance.gif',
    '10♠': 'https://media.tenor.com/M-bhqjb_sH8AAAAM/gorilla-dance.gif',
    '10♥': 'https://media.tenor.com/M-bhqjb_sH8AAAAM/gorilla-dance.gif',
    '10♦': 'https://media.tenor.com/M-bhqjb_sH8AAAAM/gorilla-dance.gif',
    '10♣': 'https://media.tenor.com/M-bhqjb_sH8AAAAM/gorilla-dance.gif',   
    '9♠': 'https://media.tenor.com/M-bhqjb_sH8AAAAM/gorilla-dance.gif',
    '9♥': 'https://media.tenor.com/M-bhqjb_sH8AAAAM/gorilla-dance.gif',
    '9♦': 'https://media.tenor.com/M-bhqjb_sH8AAAAM/gorilla-dance.gif',
    '9♣': 'https://media.tenor.com/M-bhqjb_sH8AAAAM/gorilla-dance.gif',
    '8♠': 'https://media.tenor.com/M-bhqjb_sH8AAAAM/gorilla-dance.gif',
    '8♥': 'https://media.tenor.com/M-bhqjb_sH8AAAAM/gorilla-dance.gif',
    '8♦': 'https://media.tenor.com/M-bhqjb_sH8AAAAM/gorilla-dance.gif',
    '8♣': 'https://media.tenor.com/M-bhqjb_sH8AAAAM/gorilla-dance.gif',    
    '7♠': 'https://media.tenor.com/M-bhqjb_sH8AAAAM/gorilla-dance.gif',
    '7♥': 'https://media.tenor.com/M-bhqjb_sH8AAAAM/gorilla-dance.gif',
    '7♦': 'https://media.tenor.com/M-bhqjb_sH8AAAAM/gorilla-dance.gif',
    '7♣': 'https://media.tenor.com/M-bhqjb_sH8AAAAM/gorilla-dance.gif',
    '6♠': 'https://media.tenor.com/M-bhqjb_sH8AAAAM/gorilla-dance.gif',
    '6♥': 'https://media.tenor.com/M-bhqjb_sH8AAAAM/gorilla-dance.gif',
    '6♦': 'https://media.tenor.com/M-bhqjb_sH8AAAAM/gorilla-dance.gif',
    '6♣': 'https://media.tenor.com/M-bhqjb_sH8AAAAM/gorilla-dance.gif',        
    '5♠': 'https://media.tenor.com/M-bhqjb_sH8AAAAM/gorilla-dance.gif',
    '5♥': 'https://media.tenor.com/M-bhqjb_sH8AAAAM/gorilla-dance.gif',
    '5♦': 'https://media.tenor.com/M-bhqjb_sH8AAAAM/gorilla-dance.gif',
    '5♣': 'https://media.tenor.com/M-bhqjb_sH8AAAAM/gorilla-dance.gif',
    '4♠': 'https://media.tenor.com/M-bhqjb_sH8AAAAM/gorilla-dance.gif',
    '4♥': 'https://media.tenor.com/M-bhqjb_sH8AAAAM/gorilla-dance.gif',
    '4♦': 'https://media.tenor.com/M-bhqjb_sH8AAAAM/gorilla-dance.gif',
    '4♣': 'https://media.tenor.com/M-bhqjb_sH8AAAAM/gorilla-dance.gif',    
    '3♠': 'https://media.tenor.com/M-bhqjb_sH8AAAAM/gorilla-dance.gif',
    '3♥': 'https://media.tenor.com/M-bhqjb_sH8AAAAM/gorilla-dance.gif',
    '3♦': 'https://media.tenor.com/M-bhqjb_sH8AAAAM/gorilla-dance.gif',
    '3♣': 'https://media.tenor.com/M-bhqjb_sH8AAAAM/gorilla-dance.gif',
    '2♠': 'https://media.tenor.com/M-bhqjb_sH8AAAAM/gorilla-dance.gif',
    '2♥': 'https://media.tenor.com/M-bhqjb_sH8AAAAM/gorilla-dance.gif',
    '2♦': 'https://media.tenor.com/M-bhqjb_sH8AAAAM/gorilla-dance.gif',
    '2♣': 'https://media.tenor.com/M-bhqjb_sH8AAAAM/gorilla-dance.gif',
    */    
};